version: "2"
services:
  demo-client:
    build:
      dockerfile: Dockerfile
      context: ./client
    restart: always
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=docker.for.mac.localhost:4317
      - DEMO_SERVER_ENDPOINT=http://demo-server:7080/hello
    depends_on:
      - demo-server

  demo-server:
    build:
      dockerfile: Dockerfile
      context: ./server
    restart: always
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=docker.for.mac.localhost:4317
    ports:
      - "7080"
    depends_on:
      - log-generator

  log-generator:
    platform: linux/arm64
    build:
      dockerfile: Dockerfile
      context: ./loggen
    restart: always
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://docker.for.mac.localhost:4317